#!/bin/bash
# Carregar variáveis do .env
export $(grep -v '^#' .env | xargs)

# Enviar o token como secret para o repositório do GitHub

# gh secret set AWS_PROFILE --body "$AWS_PROFILE"
# gh secret set AWS_ACCOUNT_ID --body "$AWS_ACCOUNT_ID"
# gh secret set AWS_ACCESS_KEY_ID --body "$AWS_ACCESS_KEY_ID"
# gh secret set AWS_SECRET_ACCESS_KEY --body "$AWS_SECRET_ACCESS_KEY"
# gh secret set AWS_REGION --body "$AWS_REGION"
# gh secret set TECHDOCS_S3_BUCKET_NAME --body "$TECHDOCS_BUCKET"
gh secret set ENTITY_KIND --body "$ENTITY_KIND"
gh secret set ENTITY_NAME --body "$ENTITY_NAME"
gh secret set ENTITY_NAMESPACE --body "$NAMESPACE"
# gh secret set GITHUB_TOKEN --body "$GITHUB_TOKEN"
# gh secret set GITHUB_USERNAME --body "$GITHUB_USERNAME"
# gh secret set GITHUB_EMAIL --body "$GITHUB_EMAIL"
# gh secret set GITHUB_NAME --body "$GITHUB_NAME"
# gh secret set GITHUB_COMPANY --body "$GITHUB_COMPANY"
# gh secret set GITHUB_LOCATION --body "$GITHUB_LOCATION"
# gh secret set GITHUB_BIO --body "$GITHUB_BIO"
# gh secret set GITHUB_BLOG --body "$GITHUB_BLOG"

