#!/bin/bash

# Prepare
git clone "https://github.com/carlosrobertodevops/python-advanced-template-docs.git"
cd repo

# Install @techdocs/cli, mkdocs and mkdocs plugins
npm install -g @techdocs/cli
pip install "mkdocs-techdocs-core==1.*"

# Generate
techdocs-cli generate --no-docker

# Publish
techdocs-cli publish \
	--publisher-type awsS3 \
	--storage-name $TECHDOCS_BUCKET \
	--entity $NAMESPACE/$KIND/$NAME

rm -rf "./python-advanced-template-docs"
rm -rf "./site/"